name: Build CV

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          libpango-1.0-0 \
          libpangoft2-1.0-0 \
          libharfbuzz0b \
          libffi-dev \
          libjpeg-dev \
          libopenjp2-7-dev \
          libgdk-pixbuf2.0-0

    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run tests
      run: pytest test_cv.py -v

  build:
    name: Build HTML and PDF
    runs-on: ubuntu-latest
    needs: test

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          libpango-1.0-0 \
          libpangoft2-1.0-0 \
          libharfbuzz0b \
          libffi-dev \
          libjpeg-dev \
          libopenjp2-7-dev \
          libgdk-pixbuf2.0-0

    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Build HTML and PDF
      run: python build.py

    - name: Verify outputs
      run: |
        ls -lh cv.html cv.pdf
        test -f cv.html || exit 1
        test -f cv.pdf || exit 1
        test -s cv.html || exit 1
        test -s cv.pdf || exit 1

    - name: Upload HTML artifact
      uses: actions/upload-artifact@v4
      with:
        name: cv-html
        path: cv.html
        retention-days: 90

    - name: Upload PDF artifact
      uses: actions/upload-artifact@v4
      with:
        name: cv-pdf
        path: cv.pdf
        retention-days: 90

    - name: Upload both formats
      uses: actions/upload-artifact@v4
      with:
        name: cv-all-formats
        path: |
          cv.html
          cv.pdf
        retention-days: 90
